hl.on("hyprland.start", function()
    hl.exec_cmd("vesktop")
    hl.exec_cmd("Telegram")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("sleep 10 && bongocat -c ~/.config/bongocat/bongocat.conf")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("systemctl --user restart mpd-mpris mpdscribble mpd-discord-rpc")
end)
